site_name: Web interfaces for the ARM mbed Device Connector
theme: readthedocs
use directory_urls: false
pages:
- ['index.md','ARM mbed Device Connector','Introduction to the ARM mbed Device Connector API']
- ['api-reference.md','mbed Device Connector API Reference','mbed Device Connector API Reference']
- ['tutorials_intro.md','Tutorials','Introduction']
- ['cloud_amazon.md','Tutorials','Amazon']
- ['cloud_azure.md','Tutorials','Azure']
- ['cloud_watson.md','Tutorials','Watson']

