site_name: Web interfaces for the ARM mbed Device Connector
theme: readthedocs
use directory_urls: false
pages:
- ['index.md','ARM mbed Device Connector', Introduction to the ARM mbed Device Connector']
- ['connector-web-interfaces.md','mbed Device Connector Web Interfaces','Overview to the Web Interfaces']
